services:
  patient-db-server:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: ${PATIENT_DB_USER}
      POSTGRES_PASSWORD: ${PATIENT_DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "5432:5432"
    volumes:
      - patient-db-data:/var/lib/postgresql/data
      - ./microservice-patient/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: "pg_isready -h patient-db-server -p 5432 -U $${POSTGRES_USER}"
      interval: 1s
      timeout: 1s
      retries: 60


volumes:
  patient-db-data: