services:
  patient-db-server:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: ${PATIENT_DB_USER}
      POSTGRES_PASSWORD: ${PATIENT_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - patient-db-data:/var/lib/postgresql/data
      - ./microservice-patient/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: "pg_isready -h patient-db-server -p 5432 -U $${POSTGRES_USER}"
      interval: 10s
      timeout: 5s
      retries: 5


  note-db-server:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: notedb
      MONGO_INITDB_ROOT_USERNAME: ${NOTE_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${NOTE_DB_PASSWORD}
    volumes:
      - note-db-data:/data/db
      - note-db-config:/data/configdb
      - ./microservice-note/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mongosh --quiet --eval 'db.runCommand({ ping: 1 })'"
      interval: 10s
      timeout: 5s
      retries: 5



volumes:
  patient-db-data:
  note-db-data:
  note-db-config: