services:
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      ENCRYPT_KEY: ${ENCRYPT_KEY}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    healthcheck:
        test: "wget --spider http://localhost:8000/actuator/health"
        interval: 1s
        timeout: 1s
        retries: 60


  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: "wget --spider http://localhost:8761/actuator/health"
      interval: 1s
      timeout: 1s
      retries: 60


  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: "wget --spider http://localhost:8100/actuator/health"
      interval: 1s
      timeout: 1s
      retries: 60


  patient-db-server:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: ${PATIENT_DB_USER}
      POSTGRES_PASSWORD: ${PATIENT_DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "5432:5432"
    volumes:
      - patient-db-data:/var/lib/postgresql/data
      - ./microservice-patient/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: "pg_isready -h patient-db-server -p 5432 -U $${POSTGRES_USER}"
      interval: 1s
      timeout: 1s
      retries: 60


  patient-api:
    build:
      context: ./microservice-patient
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    deploy:
      replicas: 1
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      patient-db-server:
        condition: service_healthy
      gateway-server:
        condition: service_healthy
    healthcheck:
      test: "wget --spider http://localhost:9000/actuator/health"
      interval: 1s
      timeout: 1s
      retries: 60


  client-ui:
    build:
      context: ./microservice-clientui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    depends_on:
      config-server:
        condition: service_healthy
      gateway-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      patient-db-server:
        condition: service_healthy
      patient-api:
        condition: service_healthy
    healthcheck:
      test: "wget --spider http://localhost:8080/actuator/health"
      interval: 1s
      timeout: 1s
      retries: 60


volumes:
  patient-db-data: