services:
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      ENCRYPT_KEY: ${ENCRYPT_KEY}
    healthcheck:
        test: "wget --spider http://localhost:8000/actuator/health"
        interval: 1s
        timeout: 1s
        retries: 30


  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: "wget --spider http://localhost:8761/actuator/health"
      interval: 1s
      timeout: 1s
      retries: 30


  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: "wget --spider http://localhost:8100/actuator/health"
      interval: 1s
      timeout: 1s
      retries: 30


  patient-db-server:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: ${PATIENT_DB_USER}
      POSTGRES_PASSWORD: ${PATIENT_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - patient-db-data:/var/lib/postgresql/data
      - ./microservice-patient/initdb:/docker-entrypoint-initdb.d
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: "pg_isready -h patient-db-server -p 5432 -U $${POSTGRES_USER}"
      interval: 1s
      timeout: 1s
      retries: 30


  patient-api:
    build:
      context: ./microservice-patient
      dockerfile: Dockerfile
    ports:
      - "0:9000"
    deploy:
      replicas: 2
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      patient-db-server:
        condition: service_healthy
      gateway-server:
        condition: service_healthy
    healthcheck:
      test: "wget --spider http://localhost:9000/actuator/health"
      interval: 1s
      timeout: 1s
      retries: 30


volumes:
  patient-db-data: