spring:
  application:
    name: microservice-patient

  datasource:
    url: jdbc:postgresql://${PATIENT_DB_HOST}:${PATIENT_DB_PORT}/${PATIENT_DB_NAME}
    username: ${PATIENT_DB_USER}
    password: ${PATIENT_DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update