# Server configuration
server:
  port: 8000

# Spring application configuration
spring:
  application:
    name: config-server

  # Spring Cloud Config Server repository configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maximedrouault/medilabo-config-server-repo.git
          clone-on-start: true

# Spring cloud config server configuration
encrypt:
  key: ${ENCRYPT_KEY}

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "health"